# Generated by Django 2.2 on 2020-04-22 09:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
