# Generated by Django 2.2.8 on 2020-05-18 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200422_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'publication_date', 'ordering': ['-publication_date'], 'permissions': (('can_view_all', 'Can view all entries'), ('can_change_status', 'Can change status'), ('can_change_author', 'Can change authors(s)')), 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 9, 47, 3, 382225), verbose_name='last update date'),
        ),
    ]
